services:
  mariadb:
    image: 'mariadb:latest'
    environment:
      MYSQL_DATABASE : stirshaken
      MYSQL_PASSWORD : secret
      MYSQL_USER: stshuser
      MYSQL_ROOT_PASSWORD : secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'
volumes:
  db_data: